site_name: 西安交大生存指南

repo_name: SurviveXJTU
repo_url: https://github.com/XiStudyGroup/SurviveXJTU/

copyright: Copyright &copy; 2024-present <a href="https://github.com/Axi404" target="_blank" rel="noopener noreferrer">Axi404</a>

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true
  favicon: images/favicon.ico
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
    - content.code.annotation
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: 'Times New Roman'
    code: 'Fira Code'
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Axi404

plugins:
  - search:
      lang:
        - zh
        - en

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark

nav:
  - 前言: "index.md"
  - 人生篇:
    - 前言: "人生篇/前言.md"
    - 关于西交: "人生篇/关于西交.md"
    - 你想要成为什么样的人: "人生篇/你想要成为什么样的人.md"
  - 入学篇:
    - 前言: "入学篇/前言.md"
    - 学生群: "入学篇/学生群.md"
  - 路线篇:
    - 前言: "路线篇/前言.md"
  - 研学篇:
    - 前言: "研学篇/前言.md"
  - 保研篇:
    - 前言: "保研篇/前言.md"
  # - 新生指南:
  #   - v2.0.0 beta: "人工智能新生指南2024.md"

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js